//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ATMWebSvr", ConfigurationName="ATMWebService.ATMWebSvrPortType")]
    public interface ATMWebSvrPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ATMWebSvr#averbaCTe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        ATMWebService.Retorno averbaCTe(string usuario, string senha, string codatm, string xmlCTe);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ATMWebSvr#averbaCTe", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        System.Threading.Tasks.Task<ATMWebService.Retorno> averbaCTeAsync(string usuario, string senha, string codatm, string xmlCTe);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ATMWebSvr#averbaNFe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        ATMWebService.Retorno averbaNFe(string usuario, string senha, string codatm, string xmlNFe);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ATMWebSvr#averbaNFe", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        System.Threading.Tasks.Task<ATMWebService.Retorno> averbaNFeAsync(string usuario, string senha, string codatm, string xmlNFe);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ATMWebSvr#declaraMDFe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        ATMWebService.RetornoMDFe declaraMDFe(string usuario, string senha, string codatm, string xmlMDFe);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ATMWebSvr#declaraMDFe", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        System.Threading.Tasks.Task<ATMWebService.RetornoMDFe> declaraMDFeAsync(string usuario, string senha, string codatm, string xmlMDFe);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ATMWebSvr#AddBackMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string AddBackMail(string usuario, string senha, string codatm, string aplicacao, string assunto, string remetentes, string destinatarios, string corpo, string chave, string chaveresp);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ATMWebSvr#AddBackMail", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> AddBackMailAsync(string usuario, string senha, string codatm, string aplicacao, string assunto, string remetentes, string destinatarios, string corpo, string chave, string chaveresp);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class Retorno
    {
        
        private string numeroField;
        
        private string serieField;
        
        private string filialField;
        
        private string cNPJCliField;
        
        private string tpDocField;
        
        private string infAdicField;
        
        private ErroProcesso[] errosField;
        
        private SuccessProcesso averbadoField;
        
        private InfoProcesso[] infosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Serie
        {
            get
            {
                return this.serieField;
            }
            set
            {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Filial
        {
            get
            {
                return this.filialField;
            }
            set
            {
                this.filialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CNPJCli
        {
            get
            {
                return this.cNPJCliField;
            }
            set
            {
                this.cNPJCliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=4)]
        public string TpDoc
        {
            get
            {
                return this.tpDocField;
            }
            set
            {
                this.tpDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string InfAdic
        {
            get
            {
                return this.infAdicField;
            }
            set
            {
                this.infAdicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Erro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ErroProcesso[] Erros
        {
            get
            {
                return this.errosField;
            }
            set
            {
                this.errosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public SuccessProcesso Averbado
        {
            get
            {
                return this.averbadoField;
            }
            set
            {
                this.averbadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Info", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InfoProcesso[] Infos
        {
            get
            {
                return this.infosField;
            }
            set
            {
                this.infosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class ErroProcesso
    {
        
        private string codigoField;
        
        private string descricaoField;
        
        private string valorEsperadoField;
        
        private string valorInformadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ValorEsperado
        {
            get
            {
                return this.valorEsperadoField;
            }
            set
            {
                this.valorEsperadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ValorInformado
        {
            get
            {
                return this.valorInformadoField;
            }
            set
            {
                this.valorInformadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class SuccessProcessoMDFe
    {
        
        private System.DateTime dhChancelaField;
        
        private string protocoloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dhChancela
        {
            get
            {
                return this.dhChancelaField;
            }
            set
            {
                this.dhChancelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Protocolo
        {
            get
            {
                return this.protocoloField;
            }
            set
            {
                this.protocoloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class RetornoMDFe
    {
        
        private string numeroField;
        
        private string serieField;
        
        private string filialField;
        
        private ErroProcesso[] errosField;
        
        private SuccessProcessoMDFe declaradoField;
        
        private InfoProcesso[] infosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Serie
        {
            get
            {
                return this.serieField;
            }
            set
            {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Filial
        {
            get
            {
                return this.filialField;
            }
            set
            {
                this.filialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Erro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ErroProcesso[] Erros
        {
            get
            {
                return this.errosField;
            }
            set
            {
                this.errosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public SuccessProcessoMDFe Declarado
        {
            get
            {
                return this.declaradoField;
            }
            set
            {
                this.declaradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Info", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InfoProcesso[] Infos
        {
            get
            {
                return this.infosField;
            }
            set
            {
                this.infosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class InfoProcesso
    {
        
        private string codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class DadosSeguro
    {
        
        private string numeroAverbacaoField;
        
        private string cNPJSeguradoraField;
        
        private string nomeSeguradoraField;
        
        private string numApoliceField;
        
        private string tpMovField;
        
        private string tpDDRField;
        
        private string valorAverbadoField;
        
        private string ramoAverbadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumeroAverbacao
        {
            get
            {
                return this.numeroAverbacaoField;
            }
            set
            {
                this.numeroAverbacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CNPJSeguradora
        {
            get
            {
                return this.cNPJSeguradoraField;
            }
            set
            {
                this.cNPJSeguradoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NomeSeguradora
        {
            get
            {
                return this.nomeSeguradoraField;
            }
            set
            {
                this.nomeSeguradoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NumApolice
        {
            get
            {
                return this.numApoliceField;
            }
            set
            {
                this.numApoliceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TpMov
        {
            get
            {
                return this.tpMovField;
            }
            set
            {
                this.tpMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TpDDR
        {
            get
            {
                return this.tpDDRField;
            }
            set
            {
                this.tpDDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ValorAverbado
        {
            get
            {
                return this.valorAverbadoField;
            }
            set
            {
                this.valorAverbadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string RamoAverbado
        {
            get
            {
                return this.ramoAverbadoField;
            }
            set
            {
                this.ramoAverbadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class SuccessProcesso
    {
        
        private System.DateTime dhAverbacaoField;
        
        private string protocoloField;
        
        private DadosSeguro[] dadosSeguroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dhAverbacao
        {
            get
            {
                return this.dhAverbacaoField;
            }
            set
            {
                this.dhAverbacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Protocolo
        {
            get
            {
                return this.protocoloField;
            }
            set
            {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DadosSeguro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DadosSeguro[] DadosSeguro
        {
            get
            {
                return this.dadosSeguroField;
            }
            set
            {
                this.dadosSeguroField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ATMWebSvrPortTypeChannel : ATMWebService.ATMWebSvrPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ATMWebSvrPortTypeClient : System.ServiceModel.ClientBase<ATMWebService.ATMWebSvrPortType>, ATMWebService.ATMWebSvrPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ATMWebSvrPortTypeClient() : 
                base(ATMWebSvrPortTypeClient.GetDefaultBinding(), ATMWebSvrPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ATMWebSvrPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ATMWebSvrPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ATMWebSvrPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ATMWebSvrPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ATMWebSvrPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ATMWebSvrPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ATMWebSvrPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ATMWebSvrPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ATMWebSvrPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ATMWebService.Retorno averbaCTe(string usuario, string senha, string codatm, string xmlCTe)
        {
            return base.Channel.averbaCTe(usuario, senha, codatm, xmlCTe);
        }
        
        public System.Threading.Tasks.Task<ATMWebService.Retorno> averbaCTeAsync(string usuario, string senha, string codatm, string xmlCTe)
        {
            return base.Channel.averbaCTeAsync(usuario, senha, codatm, xmlCTe);
        }
        
        public ATMWebService.Retorno averbaNFe(string usuario, string senha, string codatm, string xmlNFe)
        {
            return base.Channel.averbaNFe(usuario, senha, codatm, xmlNFe);
        }
        
        public System.Threading.Tasks.Task<ATMWebService.Retorno> averbaNFeAsync(string usuario, string senha, string codatm, string xmlNFe)
        {
            return base.Channel.averbaNFeAsync(usuario, senha, codatm, xmlNFe);
        }
        
        public ATMWebService.RetornoMDFe declaraMDFe(string usuario, string senha, string codatm, string xmlMDFe)
        {
            return base.Channel.declaraMDFe(usuario, senha, codatm, xmlMDFe);
        }
        
        public System.Threading.Tasks.Task<ATMWebService.RetornoMDFe> declaraMDFeAsync(string usuario, string senha, string codatm, string xmlMDFe)
        {
            return base.Channel.declaraMDFeAsync(usuario, senha, codatm, xmlMDFe);
        }
        
        public string AddBackMail(string usuario, string senha, string codatm, string aplicacao, string assunto, string remetentes, string destinatarios, string corpo, string chave, string chaveresp)
        {
            return base.Channel.AddBackMail(usuario, senha, codatm, aplicacao, assunto, remetentes, destinatarios, corpo, chave, chaveresp);
        }
        
        public System.Threading.Tasks.Task<string> AddBackMailAsync(string usuario, string senha, string codatm, string aplicacao, string assunto, string remetentes, string destinatarios, string corpo, string chave, string chaveresp)
        {
            return base.Channel.AddBackMailAsync(usuario, senha, codatm, aplicacao, assunto, remetentes, destinatarios, corpo, chave, chaveresp);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ATMWebSvrPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ATMWebSvrPort))
            {
                return new System.ServiceModel.EndpointAddress("http://webserver.averba.com.br/20/index.soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ATMWebSvrPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ATMWebSvrPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ATMWebSvrPortTypeClient.GetEndpointAddress(EndpointConfiguration.ATMWebSvrPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ATMWebSvrPort,
        }
    }
}
